
cd opt
curl -kL https://github.com/migtools/crane/releases/download/v0.0.5/amd64-linux-crane-v0.0.5 -o amd64-linux-crane-v0.0.5
mv amd64-linux-crane-v0.0.5 /usr/local/sbin/crane
chmod +x /usr/local/sbin/crane
crane plugin-manager add OpenShiftPlugin

