FROM ubuntu:latest
RUN apt-get update && apt-get install -y curl bash
RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash && \
    mv kustomize /usr/bin && \
    chmod +x /usr/bin/kustomize