apiVersion: saasi/v1
kind: ApplicationDeployment
spec:
  ownerReferences:
  - apiVersion: saasi/v1
    kind: SaasiDeployer
    name: example
    uid: UUID
status:
  conditions:
  - lastTransitionTime: "2023-01-10T16:51:24Z"
    lastUpdateTime: "2023-01-11T10:17:09Z"
    message: Application deployment TARGET_APP scheduled to start.
    reason: NewRequest
    status: "True"
    type: Scheduled
  - lastTransitionTime: "2023-01-10T16:51:24Z"
    lastUpdateTime: "2023-01-11T10:17:09Z"
    message: Application deployment TARGET_APP scheduled to start.
    reason: Started
    status: "True"
    type: Deploying
  - lastTransitionTime: "2023-01-10T16:51:24Z"
    lastUpdateTime: "2023-01-11T10:17:09Z"
    message: Application deployment TARGET_APP scheduled to start.
    reason: Completed
    status: "True"
    type: Deployed
  # Or, in case of failure
  - lastTransitionTime: "t2"
    lastUpdateTime: "t2"
    message: Namespace NS1 not found.
    reason: Failed
    status: "False"
    type: Deployed
  # Or, in case is waiting to complete
  - lastTransitionTime: "t2"
    lastUpdateTime: "t2"
    reason: Started
    status: "False"
    type: Deployed

      # Output contains configuration files like kubeconfig
      errorMessage: "Namespace NS1 not found"
      # Output folder contains error logs
      location: deployer/applications/APP